bot:
  name: YourBotName
  token: ${TELEGRAM_BOT_TOKEN:your_telegram_bot_token}
  chatId: ${TELEGRAM_CHAT_ID:your_telegram_chat_id}

bybit:
  apiKey: ${BYBIT_API_KEY:your_bybit_api_key}
  apiSecret: ${BYBIT_API_SECRET:your_bybit_api_secret}
  url: https://api.bybit.com